### ISSUE TITLE
Autoplace cursor in the address bar when using Ctrl+Alt+T

### ISSUE THREAD

**Issue by josemam** [sblask/firefox-open-tabs-next-to-current#16] opened 2016-06-12 14:33 UTC
The cursor is not put in the location bar if the keyboard shortcut for the default behaviour is used.

**Comment by sblask** [comment] 2016-06-13 19:07
Still works for me, i.e. Ctrl+T and Ctrl+Alt+T. Can you provide more information? What version of Firefox are you using? Do you have multiprocessing enabled? Are you using any add-on that changes the new tab page?

**Comment by josemam** [comment] 2016-06-13 19:18
I use the blank page as new tab page. I run Firefox 47.0.

**Comment by sblask** [comment] 2016-06-13 19:46
Now I can reproduce your problem (I've got a separate add-on that changes the new tab page (https://github.com/sblask/firefox-bookmark-dial) where I manually set the focus). It seems to be a problem with this sdk function: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#Open_a_tab that I use here: https://github.com/sblask/firefox-open-tabs-next-to-current/blob/master/lib/helpers.js#L58 There is no option to actually set the focus and as I think the SDK is deprecated, it's unlikely that that is going to change. You could try to open issue though: https://github.com/mozilla/addon-sdk I might actually try to migrate to webextensions at some point, but I think it's still too early and I also lack the time :-(

**Comment by sblask** [comment] 2016-07-06 14:36
Closing this for now.

**Closed by sblask** 2016-07-06 14:36 UTC
